### PR TITLE
Landing page

### PR DESCRIPTION
**Pull request by ChaseC99**
Figma Designs: https://www.figma.com/file/IS4yxUBdguS1euIRbaipVL/The-Raise?node-id=29%3A214

### CODE REVIEW

**Comment by ChaseC99** [comment]
This is the 1st draft of the Landing Page! 
image

Note: this is not mobile responsive at all LOL. I'm going to work on that.

@kaeleylenard: would you mind checking out this branch and letting me what I should improve? 

Also, anyone know what these links should redirect to?
- "Get Started"
- "continue as guest"
- "Sign up or log in" <- are "sign up" and "log in" separate links or should that whole string just go to `/signup`

**Review by kaeleylenard — COMMENTED** [review]
HI this looks amazing!! Great work!

Some design pointers:
• Header and footer text need to be in Raleway
• Increase the font weight of page title (On Demand ACEs Training)
• Center align the page title, blurb, and Get Started link with the image

Clarifications with the links:
• Get started = sign in / sign up
• Continue as guest = still waiting on Gary to clarify the guest user flow
• Sign up or login will go to /signup

**Comment by ChaseC99** [comment]
Will address the header in a future PR. A lot of it needs to be revamped, including the logo.

**Comment by ChaseC99** [comment]
How should I make this look good on mobile? 

Pretty simple to just stack everything but idk what to do with the beach pic and pinwheel. Should those 2 images just become hidden?

**Comment by kaeleylenard** [comment]
Just whipped up a quick mockup in Figma for the landing page on mobile, and yup, it would be best to hide the beach pic and pinwheel to reduce clutter.

**Comment by ChaseC99** [comment]
## Landing page and footer have been mobile-ized 📱 ✨

**Comment by ChaseC99** [comment]
Any other design notes before formal code review?

**Comment by khuynh09** [comment]
Sorry for being MIA this week. This looks great my dude!!!!!!!!! This isn't a big deal but I've been using Prettier to format my code. Just an fyi, if we wanted to keep it consistent!

**Pull request merged**
